#!/bin/sh
#PBS -N NAME.bwa.aln
#PBS -l nodes=1:ppn=THREADS
#PBS -l mem=32GB
#PBS -l walltime=16:00:00
#PBS -e READS_DIR/logs/NAME.bwa.aln.stderr
#PBS -o READS_DIR/logs/NAME.bwa.aln.stdout
cd READS_DIR
bwa aln -t THREADS FASTA R1 > tmp/NAME.r1.sai
bwa aln -t THREADS FASTA R2 > tmp/NAME.r2.sai
bwa sampe -r '@RG\tID:NAME\tPL:illumina\tPU:NAME\tLB:NAME\tSM:NAME' FASTA tmp/NAME.r1.sai tmp/NAME.r2.sai R1 R2 > tmp/NAME.bwa.sam
