#!/bin/sh
#PBS -N NAME.bt2.prep_bams
#PBS -l select=1
#PBS -l mem=4GB
#PBS -l walltime=10:00:00
#PBS -e READS_DIR/logs/NAME.bt2.prep_bams.stderr
#PBS -o READS_DIR/logs/NAME.bt2.prep_bams.stdout
cd READS_DIR
samtools view -bS tmp/NAME.bt2.sam -o tmp/NAME.bt2.bam
java -jar BIN/SortSam.jar INPUT=tmp/NAME.bt2.bam OUTPUT=tmp/NAME.bt2.sorted.bam SORT_ORDER=coordinate VALIDATION_STRINGENCY=SILENT
java -jar BIN/MarkDuplicates.jar I=tmp/NAME.bt2.sorted.bam O=tmp/NAME.bt2.dup_removed.bam REMOVE_DUPLICATES=true M=tmp/NAME.bt2.mark_dups_metrics_file
cd tmp
samtools index NAME.bt2.dup_removed.bam
