#!/bin/sh
#PBS -N NAME.bwa.base_recalibrator
#PBS -l nodes=1:ppn=THREADS
#PBS -l mem=32GB
#PBS -l walltime=12:00:00
#PBS -e READS_DIR/logs/NAME.bwa.base_recalibrator.stderr
#PBS -o READS_DIR/logs/NAME.bwa.base_recalibrator.stdout
cd READS_DIR
java -jar BIN/GenomeAnalysisTK.jar -T BaseRecalibrator -R FASTA -knownSites DBSNP -I tmp/NAME.indels_realigned.bwa.bam -o tmp/NAME.recal_data.bwa.grp
java -jar BIN/GenomeAnalysisTK.jar -T PrintReads -R FASTA -BQSR tmp/NAME.recal_data.bwa.grp -I tmp/NAME.indels_realigned.bwa.bam -o tmp/NAME.BQSR.bwa.bam
