#!/bin/sh
#PBS -N NAME.bwa.genotyper.GATK
#PBS -l nodes=1:ppn=THREADS
#PBS -l mem=32GB
#PBS -l walltime=24:00:00
#PBS -e READS_DIR/logs/NAME.bwa.genotyper.GATK.stderr
#PBS -o READS_DIR/logs/NAME.bwa.genotyper.GATK.stdout
cd READS_DIR
java -jar BIN/GenomeAnalysisTK.jar -T UnifiedGenotyper -nt THREADS -R FASTA -I tmp/NAME.BQSR.bwa.bam -o NAME.bwa.raw.snv.vcf   -glm SNP   -D DBSNP
java -jar BIN/GenomeAnalysisTK.jar -T UnifiedGenotyper -nt THREADS -R FASTA -I tmp/NAME.BQSR.bwa.bam -o NAME.bwa.raw.indel.vcf -glm INDEL -D DBSNP
