#!/bin/sh
#PBS -N NAME.bwa.base_recalibrator
#PBS -l nodes=1:ppn=THREADS
#PBS -l mem=32GB
#PBS -l walltime=24:00:00
#PBS -e /work/unmc_ngs/acornish/NAME.bwa.base_recalibrator.stderr
#PBS -o /work/unmc_ngs/acornish/NAME.bwa.base_recalibrator.stdout
cd READS_DIR
BIN/GenomeAnalysisTK.jar -T UnifiedGenotyper -nt THREADS -R REF -I tmp/NAME.BQSR.bwa.bam -o NAME.raw.snv.vcf -glm SNP -D DBSNP
BIN/GenomeAnalysisTK.jar -T UnifiedGenotyper -nt THREADS -R REF -I tmp/NAME.BQSR.bwa.bam -o NAME.raw.indel.vcf -glm INDEL -D DBSNP
